### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sundarvc** [spring-projects/spring-security-saml#500]
Hi ,

I am trying to follow the build instructions give here but I am facing issues. Do I need JDK 1.6 or will JDK 11 or 13 work ?
When I run ./gradlew build install I get compilation errors with JDK 11 .

Task 'install' not found in root project 'spring-security-saml'.

then, with just build task

springframework/security/saml/trust/httpclient/TLSProtocolSocketFactory.java:23: error: package javax.annotation does not exist
import javax.annotation.PostConstruct;
                       ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
3 warnings

Thanks,
Sundar

**Comment by sundarvc** [comment]
I was able to get it working with latest version of JDK 1.8 .
